version: '3'
services:
  vpnserver:
    image: aron666/softether-vpnserver
    environment:
      VPN_SERVER_PASSWORD: "password"
    volumes:
      - /home/user/vpnserver:/app

      - /dev:/dev
      - /lib/modules:/lib/modules
    privileged: true
    network_mode: "host"
    cap_add:
      - ALL
    stdin_open: true
    tty: true
    restart: always

    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        TARGETARCH: amd64
